title: The Programming Language Documentation
description: Documentation for the only programming language you need

author:
  name: Aaron Delasy
  email: aaron@thelang.io
  twitter: aarondelasy

twitter:
  username: thelang_io
  card: summary

exclude: [vendor, CNAME, Gemfile, Gemfile.lock]

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    disable: true
