on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0, ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CLI
        run: curl -s https://the.delasy.com/cli@latest | bash
      - name: Lint Text
        run: scripts/lint-text.sh
      - name: Lint Code
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: scripts/lint-code.sh
