on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ubuntu:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Changed Files
        uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'space-delimited'
      - name: Lint
        run: scripts/lint ${{ steps.files.outputs.added_modified }}
