on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ubuntu:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CLI
        run: curl -s https://the.delasy.com/cli@latest | bash
      - name: Lint Text
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: scripts/lint-text.sh
