on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ubuntu:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CLI
        run: curl -s https://cdn.jsdelivr.net/gh/langthe/cli/configure | bash
      - name: Lint
        run: scripts/lint
